import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import vm from "node:vm";

const repoRoot = process.cwd();

function read(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), "utf8");
}

function extractBetween(source, start, end) {
  const startIndex = source.indexOf(start);
  assert.ok(startIndex >= 0, `expected snippet start: ${start}`);
  const endIndex = source.indexOf(end, startIndex + start.length);
  assert.ok(endIndex >= 0, `expected snippet end: ${end}`);
  return source.slice(startIndex, endIndex);
}

test("economy admin route is registered and loaded by the dashboard shell", () => {
  const routes = read("docs/js/admin-routes.js");
  const pagesFunction = read("functions/[[path]].js");
  const docsPagesFunction = read("docs/functions/[[path]].js");
  const app = read("docs/js/app.js");
  const root = read("index.html");
  const docsRoot = read("docs/index.html");

  assert.match(routes, /economy:\s*\{\s*canonical:\s*"\/economy"/);
  assert.match(routes, /aliases:\s*\["\/economy-inventory",\s*"\/inventory"\]/);
  assert.match(pagesFunction, /"\/economy"/);
  assert.match(pagesFunction, /"\/economy-inventory"/);
  assert.match(pagesFunction, /"\/inventory"/);
  assert.match(docsPagesFunction, /"\/economy"/);
  assert.match(app, /registerView\("economy"/);
  assert.match(app, /registerView\("economy",\s*\{[\s\S]*dataSource:\s*"api"/);
  assert.match(app, /dataSource:\s*config\.dataSource \|\| ""/);
  assert.match(app, /function broadcastAdminLiveData\(viewName, source = "api"\)/);
  assert.match(app, /window\.EconomyInventoryAdminView\?\.init\?\.\(\)/);
  assert.match(app, /economy:\s*"\/assets\/icons\/economy\.svg"/);
  assert.match(root, /data-view="economy">Economy \/ Inventory/);
  assert.match(root, /"js\/economy\.js"/);
  assert.match(docsRoot, /data-view="economy">Economy \/ Inventory/);
  assert.match(docsRoot, /"js\/economy\.js"/);
});

test("economy view exposes required control sections and boundary copy", () => {
  const html = read("docs/views/economy.html");

  assert.match(html, /Economy Overview \/ Identity Search/);
  assert.match(html, /Economy Settings/);
  assert.match(html, /Denominations/);
  assert.match(html, /Wallet &amp; Inventory Inspector/);
  assert.match(html, /Economy Ledger/);
  assert.match(html, /Manual Economy Actions/);
  assert.match(html, /Manual Inventory Actions/);
  assert.match(html, /Gem \/ Diamond Exchange/);
  assert.match(html, /Market Governance/);
  assert.match(html, /Participation Exclusions/);
  assert.match(html, /Inventory Events/);
  assert.match(html, /Item Definitions/);
  assert.match(html, /Danger Zone/);
  assert.match(html, /id="economy-item-create-form"/);
  assert.match(html, /id="economy-danger-zone"/);
  assert.match(html, /Reversal rows are new ledger events/);
  assert.match(html, /No storefront, trading, transfers, consumption loop/);
  assert.match(html, /ss-admin-control-section/);
  assert.match(html, /ss-economy-identity-command/);
  assert.match(html, /ss-economy-command-input-row/);
  assert.match(html, /ss-economy-identity-finder/);
  assert.match(html, /ss-economy-identity-results-panel/);
  assert.match(html, /ss-economy-inspector-shell-head/);
  assert.doesNotMatch(html, /ss-economy-master-detail/);
  assert.doesNotMatch(html, /ss-economy-master-pane/);
  assert.doesNotMatch(html, /ss-economy-detail-pane/);
  assert.match(html, /data-collapsible-section="economy-ledger"/);
  assert.match(html, /data-collapse-target="economy-actions"/);
  assert.match(html, /data-collapse-target="inventory-actions"/);
  assert.match(html, /data-collapse-target="economy-overview"/);
  assert.match(html, /data-collapse-target="economy-settings"/);
  assert.match(html, /data-collapse-target="economy-denominations"/);
  assert.match(html, /data-collapse-target="economy-identity-search"/);
  assert.match(html, /data-collapse-target="economy-participation-exclusions"/);
  assert.doesNotMatch(html, /data-collapse-target="economy-inventory"/);
  assert.match(html, /data-collapse-target="economy-market-governance"/);
  assert.match(html, /data-collapse-target="economy-item-definitions"/);
  assert.match(html, /data-collapse-target="economy-danger-zone"/);
  assert.match(html, /id="economy-identity-search-section"/);
  assert.match(html, /id="economy-participation-exclusions-section"/);
  assert.match(html, /id="economy-participation-exclusions"/);
  assert.match(html, /id="economy-settings-section"/);
  assert.match(html, /id="economy-denominations-section"/);
  assert.match(html, /id="economy-wallet-inventory-section"/);
  assert.match(html, /id="economy-ledger-section"/);
  assert.match(html, /data-audit-drawer="ledger"/);
  assert.match(html, /data-audit-drawer="inventory-events"/);
  assert.match(html, /aria-label="Close Economy Ledger drawer"/);
  assert.match(html, /aria-label="Close Inventory Events drawer"/);
  assert.doesNotMatch(html, /data-collapse-target="economy-ledger" aria-expanded="true">Collapse/);
  assert.doesNotMatch(html, /data-collapse-target="inventory-events" aria-expanded="true">Collapse/);
  assert.match(html, /data-audit-drawer-open="ledger"/);
  assert.match(html, /data-identity-selector-open/);
  assert.match(html, /id="economy-actions-section"/);
  assert.doesNotMatch(html, /id="economy-inventory-section"/);
  assert.match(html, /id="economy-inventory-events-section"/);
  assert.match(html, /id="economy-inventory-actions-section"/);
  assert.match(html, /id="economy-exchange-section"/);
  assert.match(html, /id="economy-market-governance-section"/);
  assert.match(html, /id="economy-market-governance"/);
  assert.match(html, /id="economy-item-definitions-section"/);
  assert.match(html, /id="economy-danger-zone-section"/);
  assert.doesNotMatch(html, /<div class="ss-economy-grid">/);
});

test("economy controller uses runtime authority endpoints and configurable currency model", () => {
  const js = read("docs/js/economy.js");

  assert.match(js, /IDENTITIES = "\/api\/admin\/economy\/identities"/);
  assert.match(js, /ECONOMY_EVENTS = \(identityCode\) => `\/api\/admin\/economy\/identities\/\$\{encodeURIComponent\(identityCode\)\}\/events`/);
  assert.match(js, /ECONOMY_EXCHANGE = \(identityCode\) => `\/api\/admin\/economy\/identities\/\$\{encodeURIComponent\(identityCode\)\}\/exchange`/);
  assert.match(js, /ECONOMY_EVENT_REVERSE = \(eventCode\) => `\/api\/admin\/economy\/events\/\$\{encodeURIComponent\(eventCode\)\}\/reverse`/);
  assert.match(js, /INVENTORY_EVENT_CREATE = \(identityCode\) => `\/api\/admin\/inventory\/identities\/\$\{encodeURIComponent\(identityCode\)\}\/events`/);
  assert.match(js, /INVENTORY_EVENT_REVERSE = \(eventCode\) => `\/api\/admin\/inventory\/events\/\$\{encodeURIComponent\(eventCode\)\}\/reverse`/);
  assert.match(js, /ITEM_DEFINITIONS = "\/api\/admin\/inventory\/items"/);
  assert.match(js, /ITEM_DEFINITION = \(itemCode\) => `\/api\/admin\/inventory\/items\/\$\{encodeURIComponent\(itemCode\)\}`/);
  assert.match(js, /MARKET_GOVERNANCE = "\/api\/admin\/economy\/market"/);
  assert.match(js, /MARKET_GOVERNANCE_ITEM = \(itemCode\) => `\/api\/admin\/economy\/market\/items\/\$\{encodeURIComponent\(itemCode\)\}`/);
  assert.match(js, /PARTICIPATION_EXCLUSIONS = "\/api\/admin\/exclusions"/);
  assert.match(js, /PARTICIPATION_EXCLUSIONS_SUMMARY = "\/api\/admin\/exclusions\/summary"/);
  assert.match(js, /PARTICIPATION_EXCLUSION_TARGET_SEARCH = "\/api\/admin\/exclusions\/targets\/search"/);
  assert.match(js, /PARTICIPATION_EXCLUSION_TARGET = \(targetType, targetId\) => `\/api\/admin\/exclusions\/\$\{encodeURIComponent\(targetType\)\}\/\$\{encodeURIComponent\(targetId\)\}`/);
  assert.match(js, /EXCLUSION_SCOPE_DEFS = Object\.freeze/);
  assert.match(js, /"all_bot_replies", "Block all bot replies"/);
  assert.match(js, /"xp_progression", "Block XP \/ progression"/);
  assert.match(js, /"wallet_economy", "Block wallet \/ economy"/);
  assert.match(js, /"market_exchange", "Block market \/ exchange"/);
  assert.match(js, /async function saveParticipationExclusion/);
  assert.match(js, /method: "PATCH"/);
  assert.match(js, /async function clearParticipationExclusion/);
  assert.match(js, /method: "DELETE"/);
  assert.match(js, /async function searchParticipationExclusionTargets/);
  assert.match(js, /PARTICIPATION_EXCLUSION_TARGET_SEARCH\}\?q=\$\{encodeURIComponent\(normalizedQuery\)\}.*timeoutMs: 15000/s);
  assert.match(js, /scheduleParticipationExclusionTargetSearch/);
  assert.match(js, /data-exclusion-target-index/);
  assert.match(js, /selectedTarget = payload\.target/);
  assert.match(js, /class="switch-button" aria-label="\$\{escapeHtml\(label\)\} toggle"/);
  assert.match(js, /ss-switch-inner/);
  assert.match(js, /ss-economy-exclusion-governance/);
  assert.match(js, /ss-economy-exclusion-existing/);
  assert.match(js, /function renderParticipationPolicyModal/);
  assert.match(js, /ss-economy-policy-modal/);
  assert.match(js, /ss-economy-policy-modal-body/);
  assert.match(js, /id="economy-exclusion-edit-policy"/);
  assert.match(js, /data-policy-modal-close/);
  assert.match(js, /id="economy-exclusion-save"/);
  assert.match(js, /id="economy-exclusion-clear"/);
  assert.match(js, /data-exclusion-policy-target-id/);
  assert.match(js, /id="economy-exclusion-policy-search"/);
  assert.doesNotMatch(js, /<strong>Policy editor<\/strong>/);
  assert.doesNotMatch(js, /class="ss-checkbox-wrapper ss-economy-exclusion-toggle"/);
  assert.match(js, /loadParticipationExclusionSummary/);
  assert.match(js, /ECONOMY_SETTINGS = "\/api\/admin\/economy\/settings"/);
  assert.match(js, /ECONOMY_DENOMINATIONS = "\/api\/admin\/economy\/denominations"/);
  assert.match(js, /PUBLIC_GAME_BACKUP = "\/api\/admin\/public-game-authority\/backup"/);
  assert.match(js, /PUBLIC_GAME_RESET = "\/api\/admin\/public-game-authority\/reset"/);
  assert.match(js, /currency_unit_label:\s*"Credit"/);
  assert.match(js, /currency_symbol_path:\s*"assets\/games\/currencyunit\.svg"/);
  assert.match(js, /function identityUserCode/);
  assert.match(js, /identity\.user_code \|\|[\s\S]*identity\.canonical_user_code \|\|[\s\S]*identity\.account_user_code/);
  assert.match(js, /Manual economy actions require a reason/);
  assert.match(js, /Economy reversal requires an event code and reason/);
  assert.match(js, /Manual inventory actions require a reason/);
  assert.match(js, /Inventory reversal requires an event code and reason/);
  assert.match(js, /Item definition metadata changes require a reason/);
  assert.match(js, /Market governance changes require a reason/);
  assert.match(js, /New item definitions require a reason/);
  assert.match(js, /Reset requires the exact confirmation phrase and a reason/);
  assert.match(js, /Economy settings changes require a reason/);
  assert.match(js, /activeFieldValue\("#economy-actions \.ss-economy-action-grid", "#economy-action-reason"\)/);
  assert.match(js, /body: JSON\.stringify\(\{ event_type: eventType, amount_delta: amount, reason_text: reason \}\)/);
  assert.match(js, /activeFieldValue\("#economy-inventory-actions \.ss-economy-action-grid", "#inventory-action-reason"\)/);
  assert.match(js, /body: JSON\.stringify\(\{ event_type: eventType, item_code: itemCode, quantity_delta: quantity, reason_text: reason \}\)/);
  assert.match(js, /activeFieldValue\("#economy-exchange-actions \.ss-economy-exchange-grid", "#economy-exchange-reason"\)/);
  assert.match(js, /body: JSON\.stringify\(\{ identity_code: state\.selectedIdentityCode, item_code: itemCode, quantity, reason_text: reason \}\)/);
  assert.match(js, /activeFieldValue\("#economy-actions \.ss-economy-reversal-box", "#economy-reversal-reason"\)/);
  assert.match(js, /body: JSON\.stringify\(\{ reason_text: reason \}\)/);
  assert.match(js, /activeFieldValue\("#economy-inventory-actions \.ss-economy-reversal-box", "#inventory-reversal-reason"\)/);
  assert.match(js, /IDENTITY_PAGE_SIZE = 10/);
  assert.match(js, /IDENTITY_PAGE_SIZE_OPTIONS = \[10, 25, 50, 100\]/);
  assert.match(js, /identityPageSize: IDENTITY_PAGE_SIZE/);
  assert.match(js, /inventoryViewMode: "cards"/);
  assert.match(js, /inventorySearch: ""/);
  assert.match(js, /id="economy-identity-page-size"/);
  assert.match(js, /function identityPageSizeOptions\(\)/);
  assert.match(js, /data-inspector-inventory-view="cards"/);
  assert.match(js, /data-inspector-inventory-view="list"/);
  assert.match(js, /id="economy-inspector-inventory-search"/);
  assert.match(js, /ss-economy-inventory-gallery/);
  assert.match(js, /ss-economy-inventory-list-view/);
  assert.match(js, /ss-economy-selected-identity-summary/);
  assert.match(js, /EVENT_PAGE_SIZE = 8/);
  assert.match(js, /DEFAULT_ITEM_PAGE_SIZE = 20/);
  assert.match(js, /ITEM_PAGE_SIZE_OPTIONS = \[5, 10, 20, 50, 100\]/);
  assert.match(js, /itemPageSize: DEFAULT_ITEM_PAGE_SIZE/);
  assert.match(js, /data-economy-page/);
  assert.match(js, /ss-economy-item-editor/);
  assert.match(js, /renderDenominationBreakdown\(wallet\)/);
  assert.match(js, /PUBLIC_IDENTITY_UNASSIGN = "\/api\/admin\/public-identities\/reconciliation\/unassign"/);
  assert.match(js, /function renderPublicIdentityChips/);
  assert.match(js, /data-public-identity-unassign-chip/);
  assert.match(js, /Public identity unassign requires a reason\/note/);
  assert.match(js, /body: JSON\.stringify\(\{ identity_code: identityCode, account_id: accountId, reason \}\)/);
  assert.match(js, /wallet\.balance_total_credits \?\? wallet\.balance_current/);
  assert.match(js, /wallet\.cash_balance_credits \?\? wallet\.balance_current/);
  assert.match(js, /wallet\.held_value_credits \?\? 0/);
  assert.match(js, /function formatCompactNumber\(value\)/);
  assert.match(js, /function renderWalletMoneyValue\(value, options = \{\}\)/);
  assert.match(js, /compact\.toFixed\(1\)\.replace\(/);
  assert.match(js, /ss-economy-wallet-money-main/);
  assert.match(js, /category: readField\("category"\)/);
  assert.match(js, /categoryPresets/);
  assert.match(js, /itemCategories/);
  assert.match(js, /function itemCategoryOptions/);
  assert.match(js, /const seenLabels = new Set\(\)/);
  assert.match(js, /normalizedValue === "weapon"/);
  assert.match(js, /slugCode\(candidate\.code \|\| candidate\.id \|\| candidate\.label\) === "weapons"/);
  assert.match(js, /function generatedItemCode/);
  assert.match(js, /function syncGeneratedItemCodePreview/);
  assert.match(js, /function updateItemCreateFieldErrors/);
  assert.match(js, /fieldErrorMap\(err\)/);
  assert.match(js, /rarityPresets/);
  assert.match(js, /function presetOptions/);
  assert.match(js, /GAME_ASSETS = "\/api\/admin\/economy\/assets\/games"/);
  assert.match(js, /GAME_ASSET_DEFINITIONS = "\/api\/admin\/economy\/assets\/games\/definitions"/);
  assert.match(js, /GAME_ASSET_DEFINITION = \(assetPathValue\) => `\/api\/admin\/economy\/assets\/games\/definitions\/\$\{encodeURIComponent\(assetPathValue\)\}`/);
  assert.match(js, /GAME_ASSET_UPLOAD = "\/api\/admin\/economy\/assets\/games\/upload"/);
  assert.match(js, /GAME_ASSET_FILES = "\/assets\/games\/asset-files\.json"/);
  assert.match(js, /GAME_ASSET_CATALOG = "\/assets\/games\/asset-catalog\.json"/);
  assert.match(js, /IMAGE_EXTENSION_PATTERN = \/\\\.\(bmp\|gif\|jpe\?g\|png\|svg\|webp\)/);
  assert.match(js, /function normalizeItemIconPath\(path\)/);
  assert.ok(js.includes('replace(/\\\\/g, "/")'));
  assert.ok(js.includes('replace(/^docs\\\\/i, "")') || js.includes('replace(/^docs\\/+'));
  assert.ok(js.includes('assets\\/games\\/(.+)'));
  assert.match(js, /function renderAssetPicker\(\)/);
  assert.match(js, /function renderAssetPickerSurface\(\{ integrated = false \} = \{\}\)/);
  assert.match(js, /function usesUnifiedItemAssetSection\(\)/);
  assert.match(js, /state\.itemEditorSection = "assets"/);
  assert.match(js, /renderAssetPickerSurface\(\{ integrated: true \}\)/);
  assert.match(js, /ss-economy-asset-dialog--integrated/);
  assert.match(js, /function renderBundledAssetGrid\(assets, selectedPath\)/);
  assert.match(js, /function renderAssetPreviewAside\(previewPath\)/);
  assert.match(js, /function refreshIntegratedAssetFilterResults\(\)/);
  assert.match(js, /data-asset-results/);
  assert.match(js, /data-asset-preview/);
  assert.match(js, /modal\.className = "ss-economy-asset-modal"/);
  assert.match(js, /modal\.setAttribute\("role", "dialog"\)/);
  assert.match(js, /function renderAssetSourceTab\(mode, label\)/);
  assert.match(js, /document\.querySelectorAll\("#economy-asset-picker"\)/);
  assert.match(js, /aria-label="Close asset selector"/);
  assert.match(js, /Return to Details/);
  assert.match(js, /ss-economy-asset-close"[\s\S]*<span aria-hidden="true"><\/span>/);
  assert.match(js, /data-asset-close>Cancel<\/button>/);
  assert.match(js, /event\.key === "Escape" && state\.assetPicker\.open/);
  assert.match(js, /role="tab" aria-selected="\$\{active \? "true" : "false"\}"/);
  assert.match(js, /renderAssetSourceTab\("bundled", "Choose existing asset"\)/);
  assert.match(js, /renderAssetSourceTab\("define", "Define\/upload new asset"\)/);
  assert.match(js, /renderAssetSourceTab\("reconcile", "Reconcile existing files"\)/);
  assert.match(js, /renderAssetSourceTab\("custom", "External URL"\)/);
  assert.match(js, /data-asset-mode="\$\{escapeHtml\(mode\)\}"/);
  assert.match(js, /data-asset-save-definition/);
  assert.match(js, /data-asset-edit-definition/);
  assert.match(js, /data-asset-remove-definition/);
  assert.match(js, /Remove listing/);
  assert.match(js, /Physical files are not deleted/);
  assert.match(js, /data-asset-upload/);
  assert.match(js, /data-asset-define-path/);
  assert.match(js, /data-asset-use/);
  assert.match(js, /const canUseAsset = Boolean\(useValue\)/);
  assert.match(js, /function renderItemEditorNav\(\)/);
  assert.match(js, /Details/);
  assert.match(js, /Icon & Assets/);
  assert.match(js, /Public Copy/);
  assert.match(js, /Admin Notes/);
  assert.match(js, /function itemEditorSteps\(\)/);
  assert.match(js, /data-item-editor-step="previous"/);
  assert.match(js, /data-item-editor-step="next"/);
  assert.match(js, /generatedItemCodeDraftState\(draft\)/);
  assert.match(js, /item_code: generated\.itemCode/);
  assert.match(js, /item_name: generated\.label/);
  assert.match(js, /short_public_description/);
  assert.match(js, /tooltip_public_description/);
  assert.match(js, /contextual_note/);
  assert.match(js, /function renderItemDefinitionsToolbar\(pageInfo\)/);
  assert.match(js, /function renderMarketGovernance\(\)/);
  assert.match(js, /ss-economy-management-toolbar ss-economy-item-list-toolbar/);
  assert.match(js, /ss-economy-management-toolbar ss-economy-market-toolbar/);
  assert.match(js, /ss-economy-management-head/);
  assert.match(js, /ss-economy-management-search/);
  assert.match(js, /ss-economy-management-controls/);
  assert.match(js, /ss-economy-management-controls-left/);
  assert.match(js, /ss-economy-management-controls-right/);
  assert.match(js, /function renderMarketGovernanceModal\(\)/);
  assert.match(js, /ss-economy-market-modal/);
  assert.match(js, /ss-economy-market-editor-modal-body/);
  assert.match(js, /ss-economy-market-reason-card/);
  assert.match(js, /data-market-modal-close/);
  assert.match(js, /Market Sale Controls/);
  assert.match(js, /Exchange Controls/);
  assert.match(js, /Stock \/ Availability/);
  assert.match(js, /Item Context/);
  assert.match(js, /Admin Reason \/ Save Note/);
  assert.match(js, /itemSearch: ""/);
  assert.match(js, /itemViewMode: "cards"/);
  assert.match(js, /marketViewMode: "cards"/);
  assert.match(js, /marketPageSize: DEFAULT_ITEM_PAGE_SIZE/);
  assert.match(js, /bulkEditor:\s*\{/);
  assert.match(js, /function renderBulkEditorModal\(\)/);
  assert.match(js, /ss-economy-bulk-head/);
  assert.match(js, /ss-economy-bulk-title/);
  assert.match(js, /ss-economy-bulk-chip-row/);
  assert.match(js, /dirty selected/);
  assert.match(js, /visible rows/);
  assert.match(js, /function applyBulkEditor\(\)/);
  assert.match(js, /data-bulk-open="market"/);
  assert.match(js, /data-bulk-open="inventory"/);
  assert.match(js, /data-bulk-open="market"[\s\S]*economy-market-page-size/);
  assert.match(js, /data-bulk-open="inventory"[\s\S]*economy-item-page-size/);
  assert.match(js, /await requestJson\(MARKET_GOVERNANCE_ITEM\(key\)/);
  assert.match(js, /await requestJson\(ITEM_DEFINITION\(key\)/);
  assert.match(js, /window\.confirm\?\.\(`Apply \$\{dirtySelected\.length\}/);
  assert.match(js, /data-audit-drawer-open="ledger"/);
  assert.match(js, /state\.auditDrawer = text\(auditOpenButton\.dataset\.auditDrawerOpen\)/);
  assert.match(js, /streamsuites:economy-audit-drawer/);
  assert.match(js, /function announceApiHydration\(\)/);
  assert.match(js, /streamsuites:admin-live-data/);
  assert.match(js, /function highlightInspectorSelection\(\)/);
  assert.match(js, /economy-wallet-inventory-section/);
  assert.match(js, /scrollIntoView\(\{ behavior: "smooth", block: "start" \}\)/);
  assert.match(js, /is-selection-highlighted/);
  assert.match(js, /id="economy-item-search"/);
  assert.match(js, /data-item-view="cards"/);
  assert.match(js, /data-item-view="list"/);
  assert.match(js, /data-market-view="cards"/);
  assert.match(js, /data-market-view="list"/);
  assert.match(js, /id="economy-market-page-size"/);
  assert.match(js, /kind === "market"/);
  assert.match(js, /ss-economy-card-grid/);
  assert.match(js, /ss-economy-market-filter-row/);
  assert.match(js, /ss-economy-market-filter-group/);
  assert.match(js, /ss-economy-market-filter ss-checkbox-wrapper/);
  assert.match(js, /ss-economy-management-count/);
  assert.match(js, /data-market-field="market_price_stekels"/);
  assert.match(js, /data-market-field="exchange_value_stekels"/);
  assert.match(js, /data-market-field="item_type"/);
  assert.match(js, /data-market-save="\$\{escapeHtml\(item\.item_code\)\}"/);
  assert.match(js, /body: JSON\.stringify\(\{ item, reason_text: reason \}\)/);
  assert.doesNotMatch(js, /const isEditing = state\.marketEditorCode === item\.item_code/);
  assert.match(js, /isArchived: item\.is_enabled === false/);
  assert.match(js, /model\.isArchived \? " is-archived" : ""/);
  assert.match(js, /model\.isArchived \? "archived \/ disabled" : "enabled"/);
  assert.match(js, /ss-economy-item-chip-archived/);
  assert.match(js, /model\.isArchived \? "Archived" : "Archive"/);
  assert.match(js, /id="economy-item-page-size"/);
  assert.match(js, /state\.itemPageSize = ITEM_PAGE_SIZE_OPTIONS\.includes\(nextSize\) \? nextSize : DEFAULT_ITEM_PAGE_SIZE/);
  assert.match(js, /state\.itemPage = 1/);
  assert.match(js, /isLikelyImageUrl/);
  assert.match(js, /function saveAssetDefinitionFromPicker\(\)/);
  assert.match(js, /method: editingPath \? "PATCH" : "POST"/);
  assert.match(js, /function removeAssetDefinitionListing\(pathValue\)/);
  assert.match(js, /method: "DELETE"/);
  assert.match(js, /physical image file was not deleted/);
  assert.match(js, /function uploadAssetFromPicker\(\)/);
  assert.match(js, /Runtime\/Auth asset upload API is unavailable/);
  assert.match(js, /item_code: generated\.itemCode/);
  assert.match(js, /chat_alias: chatAlias/);
  assert.match(js, /reason_text: reason/);
  assert.match(js, /is_enabled: readField\("is_enabled"\) !== "false"/);
  assert.doesNotMatch(js, /localStorage/);
  assert.doesNotMatch(js, /storefront|trading|transfer|consume item/i);
});

test("manual inventory actions include searchable item picker and read-only selected item preview", () => {
  const js = read("docs/js/economy.js");
  const css = read("docs/css/components.css");

  assert.match(js, /manualInventorySearch: ""/);
  assert.match(js, /function manualInventorySearchText\(item = \{\}\)/);
  assert.match(js, /id="inventory-action-item-search"/);
  assert.match(js, /id="inventory-action-item-suggestions"/);
  assert.match(js, /data-inventory-action-pick/);
  assert.match(js, /function renderManualInventoryPreview\(\)/);
  assert.match(js, /id="inventory-action-item-preview"/);
  assert.match(js, /selectManualInventoryItem\(text\(event\.target\.value\)\)/);
  assert.match(js, /event\.key === "ArrowDown"[\s\S]*manualInventoryHighlightedIndex/);
  assert.match(js, /event\.key === "ArrowUp"[\s\S]*manualInventoryHighlightedIndex/);
  assert.match(js, /event\.key === "Enter"[\s\S]*selectManualInventoryItem/);
  assert.match(js, /event\.key === "Escape"[\s\S]*manualInventorySuggestionsOpen = false/);
  assert.match(js, /const itemCode = activeFieldValue\("#economy-inventory-actions \.ss-economy-action-grid", "#inventory-action-item"\);/);
  assert.match(js, /body: JSON\.stringify\(\{ event_type: eventType, item_code: itemCode, quantity_delta: quantity, reason_text: reason \}\)/);
  assert.match(css, /\.ss-economy-item-picker-results/);
  assert.match(css, /\.ss-economy-manual-item-preview-card/);
});

test("economy manual and reversal controls read visible reason fields", () => {
  const js = read("docs/js/economy.js");

  assert.match(js, /function activeFieldValue\(formSelector, fieldSelector\)/);
  assert.match(js, /const reason = activeFieldValue\("#economy-actions \.ss-economy-action-grid", "#economy-action-reason"\);/);
  assert.match(js, /const reason = activeFieldValue\("#economy-inventory-actions \.ss-economy-action-grid", "#inventory-action-reason"\);/);
  assert.match(js, /const reason = activeFieldValue\("#economy-actions \.ss-economy-reversal-box", "#economy-reversal-reason"\);/);
  assert.match(js, /const reason = activeFieldValue\("#economy-inventory-actions \.ss-economy-reversal-box", "#inventory-reversal-reason"\);/);
  assert.match(js, /const eventType = activeFieldValue\("#economy-actions \.ss-economy-action-grid", "#economy-action-type"\);/);
  assert.match(js, /<option value="grant">Grant<\/option><option value="penalty">Penalty<\/option><option value="adjustment">Adjustment<\/option>/);
  assert.match(js, /const eventType = activeFieldValue\("#economy-inventory-actions \.ss-economy-action-grid", "#inventory-action-type"\);/);
  assert.match(js, /<option value="grant">Grant<\/option><option value="remove">Remove<\/option><option value="adjustment">Adjust<\/option>/);
});

test("item definition save reads the visible editor reason and sends reason_text", () => {
  const js = read("docs/js/economy.js");

  assert.match(js, /function \$\(id\) \{[\s\S]*value\.startsWith\("#"\) \? value\.slice\(1\) : value/);
  assert.match(js, /const row = button\.closest\("\.ss-economy-item-definition"\);/);
  assert.match(js, /captureItemEditorDraft\(\);/);
  assert.match(js, /const draft = editItemEditorDraft\(item, itemDefinitionViewModel\(item\)\);/);
  assert.match(js, /const readField = \(field\) => text\(row\?\.querySelector\(`\[data-item-field="\$\{field\}"\]`\)\?\.value \|\| draft\[field\]\);/);
  assert.match(js, /const existing = state\.itemEditorDrafts\[key\] \|\| \{\};/);
  assert.match(js, /function editItemEditorDraft\(item = \{\}, model = itemDefinitionViewModel\(item\)\)/);
  assert.match(js, /const readMounted = \(selector\) => \{/);
  assert.match(js, /const mergeMounted = \(selectors\) => \{/);
  assert.match(js, /Object\.entries\(selectors\)\.forEach/);
  assert.match(js, /if \(value !== undefined\) next\[field\] = value;/);
  assert.match(js, /const reason = readField\("reason_text"\);/);
  assert.match(js, /reason_text: reason/);
  assert.match(js, /Category<select data-item-field="category">\$\{itemCategoryOptions\(draft\.category\)\}<\/select>/);
  assert.match(js, /function renderItemDefinitionModal\(\)/);
  assert.match(js, /ITEM_CREATE_EDITOR_CODE = "__create_item_definition__"/);
  assert.match(js, /class="ss-economy-item-editor-modal" role="dialog" aria-modal="true"/);
  assert.match(js, /data-item-modal-close/);
  assert.match(js, /data-item-editor-kind="\$\{create \? "create" : "edit"\}"/);
  assert.match(js, /data-item-editor-section="\$\{escapeHtml\(section\)\}"/);
  assert.match(js, /id="economy-item-create-open"/);
  assert.match(js, /state\.itemEditorCode = ITEM_CREATE_EDITOR_CODE/);
  assert.match(js, /state\.itemEditorCode = code;/);
  assert.match(js, /function economyOverlayOpen\(\)/);
  assert.match(js, /document\.body\?\.classList\?\.toggle\("ss-economy-modal-open", economyOverlayOpen\(\)\)/);
  assert.match(js, /item\.public_short_description/);
  assert.match(js, /item\.description/);
  assert.match(js, /item\.tooltip_public_details/);
  assert.match(js, /item\.public_details/);
  assert.match(js, /item\.details/);
  assert.match(js, /metadata\.details/);
  assert.match(js, /combat_vehicle: "Combat Vehicles"/);
  assert.match(js, /armor: "Armor"/);
  assert.match(js, /platform_badge: "Platform Badges"/);
  assert.match(js, /fish_treasure: "Fish & Treasures"/);
  assert.match(js, /function categoryDisplayLabel\(value = "", fallback = ""\)/);
  assert.match(js, /function categoryCodePrefix\(categoryValue = ""\)/);
  assert.match(js, /function itemCodeSuffix\(itemCode = ""\)/);
  assert.match(js, /function generatedEditorItemCode\(row\)/);
  assert.match(js, /function syncItemEditorCodePreview\(row\)/);
  assert.match(js, /data-item-field="item_code_suffix"/);
  assert.match(js, /data-item-code-prefix/);
  assert.match(js, /data-item-code-preview/);
  assert.match(js, /Duplicate item code\. Choose another suffix before saving\./);
  assert.match(js, /existing item-code renames are blocked until Runtime\/Auth can migrate references/i);
  assert.match(js, /marketItemTypeLabel\(item\)/);
  assert.match(js, /Rarity<select data-item-field="rarity">/);
  assert.match(js, /Public tooltip<select data-item-field="public_tooltip_enabled">/);
  assert.match(js, /Short public description<textarea data-item-field="short_description"/);
  assert.match(js, /Tooltip public details<textarea data-item-field="tooltip_description"/);
  assert.match(js, /Contextual public note<textarea data-item-field="contextual_public_note"/);
  assert.match(js, /icon_path: normalizeItemIconPath\(readField\("icon_path"\)\)/);
  assert.match(js, /public_tooltip_enabled: readField\("public_tooltip_enabled"\) !== "false"/);
  assert.match(js, /short_description: readField\("short_description"\)/);
  assert.match(js, /tooltip_description: readField\("tooltip_description"\)/);
  assert.match(js, /contextual_public_note: readField\("contextual_public_note"\)/);
  assert.match(js, /id="economy-item-code-preview"/);
  assert.match(js, /id="economy-item-create-code" type="hidden" readonly/);
  assert.match(js, /id="economy-item-create-error-reason_text"/);
  assert.match(js, /const fields = \["label", "item_name", "category", "item_code", "rarity", "chat_alias", "short_description", "tooltip_description", "reason_text", "reason"\]/);
  assert.match(js, /fieldErrorText\(errors, "reason"\)/);
  assert.match(js, /ss-field-error/);
  assert.match(js, /#economy-item-create-label, #economy-item-create-category, #economy-item-create-reason/);
  assert.match(js, /icon_path: normalizeItemIconPath\(\$\(("#economy-item-create-icon"|'economy-item-create-icon')\)\?\.value \|\| draft\.icon_path\)/);
  assert.match(js, /id="economy-item-create-short-description"/);
  assert.match(js, /id="economy-item-create-tooltip-description"/);
  assert.match(js, /id="economy-item-create-contextual-note"/);
  assert.match(js, /id="economy-item-create-public-tooltip"/);
  assert.match(js, /id="economy-item-create-chat-alias"/);
  assert.match(js, /Chat alias/);
  assert.match(js, /!buy lumber/);
  assert.match(js, /data-item-field="chat_alias"/);
  assert.match(js, /function normalizeChatAlias/);
  assert.match(js, /function chatAliasLooksValid/);
  assert.match(js, /short_description: text\(\$\(("#economy-item-create-short-description"|'economy-item-create-short-description')\)\?\.value \|\| draft\.short_description\)/);
  assert.match(js, /tooltip_description: text\(\$\(("#economy-item-create-tooltip-description"|'economy-item-create-tooltip-description')\)\?\.value \|\| draft\.tooltip_description\)/);
  assert.match(js, /body: JSON\.stringify\(\{[\s\S]*item_code: generated\.itemCode[\s\S]*reason_text: reason[\s\S]*\}\)/);
  assert.match(js, /function deleteItemDefinition\(button\)/);
  assert.match(js, /method: "DELETE"/);
  assert.match(js, /Item definition archive requires a reason/);
  assert.match(js, /Historical inventory rows are preserved/);
  assert.match(js, /no longer purchasable by chat alias/);
  assert.ok(js.includes("ss-economy-asset-browse"));
  assert.match(js, /Browse assets/);
  assert.match(js, /ss-economy-item-create-shell/);
  assert.match(js, /ss-economy-icon-card/);
  assert.match(js, /No icon configured/);
  assert.match(js, /Preview unavailable/);
  assert.doesNotMatch(js, /button\.closest\("\[data-item-code\]"\)/);
});

test("game asset catalog manifest lists bundled dashboard image assets", () => {
  const fileManifest = JSON.parse(read("docs/assets/games/asset-files.json"));
  const manifest = JSON.parse(read("docs/assets/games/asset-catalog.json"));

  assert.equal(fileManifest.asset_root, "assets/games");
  assert.ok(Array.isArray(fileManifest.items));
  assert.ok(fileManifest.supported_extensions.includes("webp"));
  assert.ok(fileManifest.supported_extensions.includes("gif"));
  assert.ok(fileManifest.supported_extensions.includes("png"));
  assert.ok(fileManifest.supported_extensions.includes("jpg"));
  assert.ok(fileManifest.supported_extensions.includes("jpeg"));
  assert.ok(fileManifest.supported_extensions.includes("bmp"));
  assert.ok(fileManifest.supported_extensions.includes("svg"));
  assert.ok(fileManifest.items.some((item) => item.path === "assets/games/sscoin.webp"));
  assert.ok(fileManifest.items.some((item) => item.path === "assets/games/currencyunit.svg"));
  assert.ok(fileManifest.items.every((item) => item.path.startsWith("assets/games/")));
  assert.ok(fileManifest.items.every((item) => item.filename !== "asset-catalog.json" && item.filename !== "asset-files.json"));
  assert.equal(manifest.asset_root, "assets/games");
  assert.ok(Array.isArray(manifest.items));
  assert.ok(manifest.items.length >= 1);
  assert.ok(manifest.items.some((item) => item.path === "assets/games/sscoin.webp"));
  assert.ok(manifest.items.every((item) => item.path.startsWith("assets/games/")));
  assert.ok(manifest.items.every((item) => item.filename && item.extension && item.label));
});

test("economy settings controls and denomination rendering are wired", () => {
  const js = read("docs/js/economy.js");

  assert.match(js, /function renderEconomySettings\(\)/);
  assert.match(js, /id="economy-setting-label"/);
  assert.match(js, /id="economy-setting-plural"/);
  assert.match(js, /id="economy-setting-symbol"/);
  assert.match(js, /id="economy-setting-reason"/);
  assert.match(js, /body: JSON\.stringify\(\{ settings, reason_text: reason \}\)/);
  assert.match(js, /function renderDenominations\(\)/);
  assert.match(js, /always_show_in_balance \? "Always shown in balance" : "Shown only when nonzero"/);
  assert.match(js, /is_high_value_unit \? "High-value unit" : "Base unit"/);
  assert.match(js, /ECONOMY_DENOMINATION = \(denominationCode\) => `\/api\/admin\/economy\/denominations\/\$\{encodeURIComponent\(denominationCode\)\}`/);
  assert.match(js, /data-denomination-code="\$\{escapeHtml\(item\.denomination_code\)\}"/);
  assert.match(js, /data-asset-target="\$\{escapeHtml\(target\)\}"/);
  assert.match(js, /data-denomination-field="icon_path"/);
  assert.match(js, /if \(input && value\) \{[\s\S]*input\.value = value;[\s\S]*syncIconPreview\(input\);/);
  assert.match(js, /function saveDenominationIcon\(button\)/);
  assert.match(js, /body: JSON\.stringify\(\{[\s\S]*denomination:\s*\{[\s\S]*icon_path: normalizeItemIconPath\(readField\("icon_path"\)\)[\s\S]*reason_text: reason[\s\S]*\}\)/);
  assert.match(js, /fieldErrorMap\(err\)/);
});

test("asset picker search restores focus across result rerenders", () => {
  const js = read("docs/js/economy.js");

  assert.match(js, /const activeElement = document\.activeElement;/);
  assert.match(js, /const restoreFocusId = activeElement\?\.id === "economy-asset-filter"/);
  assert.match(js, /target\?\.focus\?\.\(\);/);
  assert.match(js, /target\.setSelectionRange\(restoreSelectionStart, restoreSelectionEnd\);/);
  assert.match(js, /state\.assetPicker\.filter = event\.target\.value;[\s\S]*if \(!refreshIntegratedAssetFilterResults\(\)\) refreshAssetPickerView\(\);/);
  assert.match(js, /const results = container\?\.querySelector\("\[data-asset-results\]"\);/);
  assert.match(js, /results\.outerHTML = renderBundledAssetGrid\(assets, selectedPath\);/);
  assert.match(js, /preview\.outerHTML = renderAssetPreviewAside\(previewPath\);/);
});

test("economy collapsible sections default expanded", () => {
  const html = read("docs/views/economy.html");

  assert.match(html, /data-collapse-target="economy-overview" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-settings" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-denominations" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-identity-search" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-participation-exclusions" aria-expanded="true">Collapse/);
  assert.doesNotMatch(html, /data-collapse-target="economy-ledger" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-actions" aria-expanded="true">Collapse/);
  assert.doesNotMatch(html, /data-collapse-target="economy-inventory" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="inventory-actions" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-exchange" aria-expanded="true">Collapse/);
  assert.doesNotMatch(html, /data-collapse-target="inventory-events" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-market-governance" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-item-definitions" aria-expanded="true">Collapse/);
  assert.match(html, /data-collapse-target="economy-danger-zone" aria-expanded="true">Collapse/);
  assert.match(html, /ss-admin-collapse-toggle/);
  assert.match(html, /ss-admin-collapsible-body/);
  assert.doesNotMatch(html, /data-collapse-target="(?:economy-overview|economy-settings|economy-denominations|economy-identity-search|economy-participation-exclusions|economy-ledger|economy-actions|inventory-actions|economy-exchange|inventory-events|economy-market-governance|economy-item-definitions|economy-danger-zone)" aria-expanded="false"/);
});

test("economy route uses the shared top-bar section anchor row", () => {
  const app = read("docs/js/app.js");

  assert.match(app, /economy:\s*Object\.freeze\(\{/);
  assert.match(app, /storageKey:\s*"ss_economy_shell_tabs_collapsed"/);
  assert.match(app, /toggleLabel:\s*"economy section tabs"/);
  assert.match(app, /\{ id: "economy-settings-section", label: "Economy Settings" \}/);
  assert.match(app, /\{ id: "economy-denominations-section", label: "Denominations" \}/);
  assert.match(app, /\{ id: "economy-identity-search-section", label: "Wallet & Inventory" \}/);
  assert.match(app, /\{ id: "economy-participation-exclusions-section", label: "Participation Exclusions" \}/);
  assert.doesNotMatch(app, /\{ id: "economy-wallet-section", label: "Wallet" \}/);
  assert.match(app, /\{ id: "economy-ledger-section", label: "Economy Ledger" \}/);
  assert.match(app, /\{ id: "economy-actions-section", label: "Manual Economy Actions" \}/);
  assert.doesNotMatch(app, /\{ id: "economy-inventory-section", label: "Inventory" \}/);
  assert.match(app, /\{ id: "economy-inventory-events-section", label: "Inventory Events" \}/);
  assert.match(app, /\{ id: "economy-inventory-actions-section", label: "Manual Inventory Actions" \}/);
  assert.match(app, /\{ id: "economy-exchange-section", label: "Gem \/ Diamond Exchange" \}/);
  assert.match(app, /\{ id: "economy-market-governance-section", label: "Market Governance" \}/);
  assert.match(app, /\{ id: "economy-item-definitions-section", label: "Item Definitions" \}/);
  assert.match(app, /\{ id: "economy-danger-zone-section", label: "Danger Zone" \}/);
  assert.match(app, /data-accounts-shell-anchor="\$\{section\.id\}"/);
  assert.match(app, /scrollToAccountsShellSection\(sectionId\)/);
  assert.match(app, /streamsuites:economy-audit-drawer/);
  assert.match(app, /streamsuites:admin-live-data/);
  assert.match(app, /if \(!resolveSectionShellConfig\(App\.currentView\)\) return;/);
});

test("snapshot warning stays source-aware for API hydrated admin views", () => {
  const state = read("docs/js/state.js");
  const health = read("docs/js/utils/snapshot-health.js");

  assert.match(health, /function isLiveDataSource\(context = \{\}\)/);
  assert.match(health, /export function evaluateSnapshotHealth\(snapshot, context = \{\}\)/);
  assert.match(health, /source === "api"/);
  assert.match(health, /export function clearSnapshotHealthBanner\(\)/);
  assert.match(health, /streamsuites:admin-live-data/);
  assert.match(state, /evaluateSnapshotHealth\(rawSnapshot, context\)/);
  assert.match(state, /reportSnapshotHealth\(cache\.runtimeSnapshot, \{ source: "connected" \}\)/);
  assert.match(state, /reportSnapshotHealth\(sharedRaw, \{ source: "static" \}\)/);
});

test("economy styling includes compact identity rows and currency/denomination treatments", () => {
  const css = read("docs/css/components.css");
  const js = read("docs/js/economy.js");

  assert.match(css, /\.ss-economy-identity\s*\{[\s\S]*grid-template-columns:\s*42px minmax\(0,\s*1fr\)/);
  assert.match(css, /\.ss-economy-avatar\s*\{[\s\S]*width:\s*42px[\s\S]*height:\s*42px/);
  assert.match(css, /\.ss-economy-avatar img,[\s\S]*\.ss-economy-item-icon img\s*\{[\s\S]*object-fit:\s*contain/);
  assert.match(css, /\.ss-economy-currency-symbol\s*\{[\s\S]*mask:\s*var\(--economy-currency-symbol\) center \/ contain no-repeat/);
  assert.match(css, /\.ss-economy-credit-value--compact \.ss-economy-currency-symbol/);
  assert.match(css, /\.ss-economy-wallet-money\s*\{/);
  assert.match(css, /\.ss-economy-wallet-money-main\s*\{[\s\S]*font-size:\s*18px[\s\S]*white-space:\s*nowrap/);
  assert.match(css, /\.ss-economy-wallet-money-main \.ss-economy-currency-symbol\s*\{[\s\S]*width:\s*22px[\s\S]*height:\s*22px/);
  assert.match(css, /\.ss-economy-kpis \.ss-economy-wallet-money-main,\s*\.ss-economy-kpis \.ss-economy-wallet-money-main span\s*\{[\s\S]*display:\s*inline-flex[\s\S]*font-size:\s*18px/);
  assert.match(css, /\.ss-economy-wallet-money small\s*\{[\s\S]*text-transform:\s*none/);
  assert.match(css, /\.ss-economy-denomination-breakdown\s*\{/);
  assert.match(css, /\.ss-economy-denomination-chip img\s*\{[\s\S]*object-fit:\s*contain/);
  assert.match(css, /\.ss-economy-denomination-chip img\s*\{[\s\S]*width:\s*50px[\s\S]*height:\s*50px/);
  assert.match(css, /\.ss-economy-denomination-row > \.ss-economy-item-icon\s*\{[\s\S]*width:\s*86px[\s\S]*height:\s*86px/);
  assert.match(css, /\.ss-economy-denomination-row\.is-editing\s*\{/);
  assert.match(css, /\.ss-economy-denomination-editor\s*\{[\s\S]*grid-column:\s*1 \/ -1/);
  assert.match(css, /\.ss-economy-denomination-editor \.ss-economy-icon-field\s*\{[\s\S]*grid-template-columns:\s*minmax\(220px,\s*1fr\) auto/);
  assert.match(css, /\.ss-economy-denomination-editor \.ss-economy-icon-preview\s*\{[\s\S]*grid-column:\s*1 \/ -1/);
  assert.match(css, /\.ss-economy-exclusion-toggle-group\s*\{/);
  assert.match(css, /\.ss-economy-exclusion-switch\s*\{/);
  assert.match(css, /\.ss-economy-exclusion-switch\s*\{[\s\S]*grid-template-columns:\s*58px minmax\(0,\s*1fr\)/);
  assert.match(css, /\.ss-economy-exclusion-switch\s*\{[\s\S]*overflow:\s*hidden/);
  assert.match(css, /\.ss-economy-exclusion-switch \.switch-button\s*\{/);
  assert.match(css, /\.ss-economy-exclusion-switch \.switch-scale\s*\{[\s\S]*transform:\s*none/);
  assert.match(css, /\.ss-economy-exclusion-existing\s*,/);
  assert.match(css, /\.ss-economy-exclusion-policy-card\s*\{/);
  assert.match(css, /\.ss-economy-policy-modal\s*\{/);
  assert.match(css, /\.ss-economy-policy-dialog\s*\{[\s\S]*width:\s*min\(1240px,\s*100%\)/);
  assert.match(css, /\.ss-economy-policy-modal-body\s*\{/);
  assert.match(css, /\.ss-economy-exclusion-results\s*\{/);
  assert.match(css, /\.ss-economy-exclusion-context\s*\{/);
  assert.match(css, /\.ss-economy-exclusion-facts\s*\{/);
  assert.match(css, /\.ss-economy-combined-inspector\s*\{/);
  assert.match(css, /\.ss-economy-identity-command\s*\{/);
  assert.match(css, /\.ss-economy-command-input-row\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto/);
  assert.match(css, /\.ss-economy-identity-results-panel\s*\{/);
  assert.match(css, /\.ss-economy-inspector-shell-head\s*\{/);
  assert.match(css, /\.ss-economy-identity-selector-head\s*\{/);
  assert.match(css, /\.ss-economy-selected-identity-summary\s*\{[\s\S]*grid-template-columns:\s*124px minmax\(0,\s*1fr\)/);
  assert.match(css, /\.ss-economy-selected-identity-summary \.ss-economy-avatar\s*\{[\s\S]*width:\s*124px[\s\S]*height:\s*124px/);
  assert.match(css, /\.ss-economy-inventory-gallery\s*\{/);
  assert.match(css, /\.ss-economy-inventory-card \.ss-economy-item-icon\s*\{[\s\S]*width:\s*104px[\s\S]*height:\s*104px/);
  assert.match(css, /\.ss-economy-item-chip\s*\{/);
  assert.match(css, /\.ss-economy-item-chip-row\s*\{/);
  assert.match(css, /\.ss-economy-item-chip-archived\s*\{[\s\S]*background:\s*rgba\(148,\s*163,\s*184,\s*0\.16\)/);
  assert.match(css, /\.ss-economy-item-definition\.is-archived\s*\{[\s\S]*opacity:\s*0\.74/);
  assert.match(css, /\.ss-economy-item-definition\.is-archived \.ss-economy-item-icon\s*\{[\s\S]*filter:\s*grayscale\(1\)/);
  assert.match(css, /\.ss-economy-state-reversed,[\s\S]*\.ss-economy-state-reversal/);
  assert.doesNotMatch(css, /\.ss-economy-master-detail\s*\{/);
  assert.doesNotMatch(css, /\.ss-economy-master-pane\s*\{/);
  assert.doesNotMatch(css, /\.ss-economy-detail-pane\s*\{/);
  assert.match(css, /\.ss-economy-identity-finder\.is-selector-open \.ss-economy-identity-results-panel\s*\{[\s\S]*transform:\s*translateX\(0\)/);
  assert.match(css, /\.ss-economy-audit-drawer\s*\{[\s\S]*position:\s*fixed[\s\S]*transform:\s*translateX\(105%\)/);
  assert.match(css, /\.ss-economy-audit-drawer\s*\{[\s\S]*background:\s*rgb\(7,\s*12,\s*22\)/);
  assert.match(css, /\.ss-economy-identity-results-panel\s*\{[\s\S]*rgb\(5,\s*12,\s*24\)/);
  assert.match(css, /\.ss-economy-combined-inspector\.is-selection-highlighted/);
  assert.match(css, /\.ss-economy-audit-drawer\.is-open\s*\{[\s\S]*transform:\s*translateX\(0\)/);
  assert.match(css, /\.ss-economy-bulk-dialog\s*\{[\s\S]*width:\s*min\(1480px,\s*100%\)/);
  assert.match(css, /\.ss-economy-bulk-head\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto/);
  assert.match(css, /\.ss-economy-bulk-title h3\s*\{[\s\S]*font-size:\s*clamp\(24px,\s*2vw,\s*34px\)/);
  assert.match(css, /\.ss-economy-bulk-chip-row\s*\{/);
  assert.match(css, /\.ss-economy-bulk-table-wrap\s*\{[\s\S]*overflow:\s*auto/);
  assert.match(css, /\.ss-economy-item-definition-summary\s*\{[\s\S]*grid-template-columns:\s*76px minmax\(0,\s*1fr\) auto/);
  assert.match(css, /\.ss-economy-item-create-shell\s*\{/);
  assert.match(css, /\.ss-economy-item-create-grid\s*\{[\s\S]*grid-template-columns:\s*minmax\(300px,\s*1fr\) minmax\(280px,\s*0\.82fr\) minmax\(360px,\s*1\.12fr\)/);
  assert.match(css, /\.ss-economy-item-create-card--code\s*\{/);
  assert.match(css, /\.ss-economy-item-code-status\.is-error/);
  assert.match(css, /\.ss-field-error\s*\{/);
  assert.match(css, /\.ss-economy-item-create-card--icon \.ss-economy-icon-preview\s*\{[\s\S]*min-height:\s*92px/);
  assert.match(css, /\.ss-economy-item-list-toolbar\s*\{/);
  assert.match(css, /\.ss-economy-item-list-toolbar\.ss-economy-management-toolbar\s*\{[\s\S]*display:\s*grid/);
  assert.match(css, /\.ss-economy-management-toolbar\s*\{/);
  assert.match(css, /\.ss-economy-management-head\s*\{/);
  assert.match(css, /\.ss-economy-management-search label\s*\{/);
  assert.match(css, /\.ss-economy-management-controls\s*\{/);
  assert.match(css, /\.ss-economy-management-controls-left,\s*\.ss-economy-management-controls-right\s*\{/);
  assert.match(css, /\.ss-economy-item-page-size select\s*\{[\s\S]*min-width:\s*82px/);
  assert.match(css, /\.ss-economy-view-toggle\s*\{[\s\S]*flex-wrap:\s*nowrap/);
  assert.match(css, /\.ss-economy-view-toggle \.ss-btn\s*\{[\s\S]*white-space:\s*nowrap/);
  assert.match(css, /\.ss-economy-item-editor-section\s*\{[\s\S]*grid-template-columns:\s*minmax\(290px,\s*1fr\) minmax\(280px,\s*0\.8fr\) minmax\(300px,\s*0\.85fr\)/);
  assert.match(css, /\.ss-economy-item-editor-nav\s*\{/);
  assert.match(css, /\.ss-economy-item-editor-tab\.is-active\s*\{/);
  assert.match(css, /\.ss-economy-card-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(auto-fit,\s*minmax\(min\(100%,\s*390px\),\s*1fr\)\)/);
  assert.match(css, /\.ss-economy-browser-card \.ss-economy-item-definition-summary,[\s\S]*\.ss-economy-browser-card \.ss-economy-market-summary\s*\{[\s\S]*grid-template-columns:\s*88px minmax\(0,\s*1fr\)/);
  assert.match(css, /\.ss-economy-item-editor-modal\s*\{/);
  assert.match(css, /\.ss-economy-item-editor-dialog\s*\{[\s\S]*width:\s*min\(1320px,\s*100%\)/);
  assert.match(css, /\.ss-economy-modal-open\s*\{[\s\S]*overflow:\s*hidden/);
  assert.match(js, /function openItemDetailModal\(item = \{\}, kind = "item", sourceElement = null, context = \{\}\)/);
  assert.match(js, /function formatEconomyDetailTimestamp\(value\)/);
  assert.match(js, /data-item-detail-previous/);
  assert.match(js, /data-item-detail-next/);
  assert.match(js, /function navigateItemDetail\(delta\)/);
  assert.match(js, /event\.key === "ArrowLeft"[\s\S]*navigateItemDetail\(-1\)/);
  assert.match(js, /event\.key === "ArrowRight"[\s\S]*navigateItemDetail\(1\)/);
  assert.match(js, /renderItemDetailCurrencyAmount\(stat\.rawValue\)/);
  assert.match(js, /data-item-detail-open/);
  assert.match(js, /data-item-detail-kind="wallet"/);
  assert.match(js, /data-item-detail-kind="inventory"/);
  assert.match(js, /data-item-detail-kind="market"/);
  assert.match(js, /data-item-detail-kind="definition"/);
  assert.match(css, /\.ss-economy-item-detail-modal\s*\{/);
  assert.match(css, /\.ss-economy-item-detail-head\s*\{[\s\S]*grid-column:\s*1 \/ -1/);
  assert.match(css, /\.ss-economy-item-detail-nav\s*\{[\s\S]*display:\s*inline-flex/);
  assert.match(css, /\.ss-economy-item-detail-dialog\s*\{[\s\S]*grid-template-columns:\s*minmax\(280px,\s*0\.88fr\) minmax\(0,\s*1\.12fr\)/);
  assert.match(css, /\.ss-economy-item-detail-hero \.ss-economy-item-icon\s*\{[\s\S]*width:\s*min\(78%,\s*330px\)/);
  assert.match(css, /\.ss-economy-item-detail-hero \.ss-economy-item-icon\s*\{[\s\S]*border:\s*0[\s\S]*background:\s*transparent/);
  assert.match(css, /\.ss-economy-detail-currency\s*\{[\s\S]*color:\s*var\(--text-primary\)/);
  assert.match(js, /function collectEconomyItemDetailTagSources\(/);
  assert.match(js, /function appendEconomyItemDetailTagFields\(/);
  assert.match(js, /function economyItemDetailTagContainer\(/);
  assert.match(js, /function normalizeItemDetailTags\(\.\.\.sources\)/);
  assert.doesNotMatch(js, /item\.chips,\s*[\s\S]*metadata\.tags/);
  assert.match(js, /function renderItemDetailTagChips\(tags = \[\]\)/);
  assert.match(js, /function renderItemDetailMetaRow\(row = \{\}\)/);
  assert.match(js, /variant: "item-code"/);
  assert.match(js, /const tags = normalizeItemDetailTags\(\.\.\.collectEconomyItemDetailTagSources/);
  assert.match(js, /renderItemDetailTagGroup\(model\.tags\)/);
  assert.match(css, /\.ss-economy-item-detail-tags\s*\{/);
  assert.match(js, /economy-item-tag-chips/);
  assert.match(js, /economy-item-code-value/);
  assert.match(css, /\.economy-item-tag-chip\s*\{[\s\S]*SuiGenerisRg[\s\S]*font-weight:\s*400[\s\S]*rgba\(186,\s*220,\s*255/);
  assert.match(css, /\.ss-economy-item-detail-modal \.economy-item-code-value\s*\{[\s\S]*SUSEMono/);
  assert.match(css, /#economy-inventory-actions input\[type="number"\][\s\S]*color-scheme:\s*dark/);
  assert.match(css, /\.ss-economy-market-toolbar\s*\{/);
  assert.match(css, /\.ss-economy-market-filter-row\s*\{[\s\S]*justify-content:\s*space-between/);
  assert.match(css, /\.ss-economy-market-filter-group\s*\{[\s\S]*flex-wrap:\s*wrap/);
  assert.match(css, /\.ss-economy-market-filter\s*\{[\s\S]*--ss-checkbox-size:\s*13px/);
  assert.match(css, /\.ss-economy-market-filter \.ss-checkbox-text\s*\{[\s\S]*font-size:\s*0\.78rem/);
  assert.match(css, /\.ss-economy-market-count\s*\{[\s\S]*text-align:\s*right/);
  assert.match(css, /\.ss-economy-market-editor\s*\{[\s\S]*grid-template-columns:\s*repeat\(4,\s*minmax\(150px,\s*1fr\)\)/);
  assert.match(css, /\.ss-economy-market-editor-modal-body\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) minmax\(0,\s*1fr\) minmax\(300px,\s*0\.9fr\)/);
  assert.match(css, /\.ss-economy-market-editor-modal-body\s*\{[\s\S]*grid-template-areas:\s*"sale exchange context"[\s\S]*"stock reason context"/);
  assert.match(css, /\.ss-economy-market-editor-modal-body\s*\{[\s\S]*grid-auto-flow:\s*dense/);
  assert.match(css, /\.ss-economy-market-reason-card\s*\{[\s\S]*grid-area:\s*reason/);
  assert.match(css, /\.ss-economy-market-context-card\s*\{[\s\S]*grid-area:\s*context/);
  assert.match(css, /\.ss-economy-market-dialog\s*\{[\s\S]*width:\s*min\(1180px,\s*100%\)/);
  assert.match(css, /\.ss-economy-icon-field\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\) auto/);
  assert.match(css, /\.ss-economy-icon-field \.ss-economy-icon-preview\s*\{[\s\S]*grid-column:\s*1 \/ -1/);
  assert.match(css, /\.ss-economy-asset-modal\s*\{/);
  assert.doesNotMatch(css, /\.ss-economy-asset-modal\.is-embedded/);
  assert.match(css, /\.ss-economy-asset-dialog--integrated\s*\{[\s\S]*width:\s*100%/);
  assert.match(css, /\.ss-economy-asset-dialog--integrated\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1\.7fr\) minmax\(320px,\s*0\.62fr\)/);
  assert.match(css, /\.ss-economy-item-editor-section--copy,\s*\.ss-economy-item-editor-section--admin,\s*\.ss-economy-item-editor-section--assets\s*\{[\s\S]*grid-template-columns:\s*minmax\(0,\s*1fr\)/);
  assert.match(css, /\.ss-economy-asset-dialog--integrated \.ss-economy-asset-tabs,[\s\S]*\.ss-economy-asset-dialog--integrated \.ss-economy-asset-search,[\s\S]*\.ss-economy-asset-dialog--integrated \.ss-economy-asset-custom\s*\{[\s\S]*grid-column:\s*1 \/ -1/);
  assert.match(css, /\.ss-economy-asset-dialog--integrated \.ss-economy-asset-search input\s*\{[\s\S]*max-width:\s*none/);
  assert.match(css, /\.ss-economy-asset-dialog\s*\{[\s\S]*width:\s*min\(1160px,\s*100%\)/);
  assert.match(css, /\.ss-economy-asset-head\s*\{[\s\S]*grid-row:\s*1/);
  assert.match(css, /\.ss-economy-asset-close span\s*\{[\s\S]*-webkit-mask-image:\s*url\("\/assets\/icons\/ui\/cross\.svg"\)/);
  assert.match(css, /\.ss-economy-asset-close:hover,[\s\S]*\.ss-economy-asset-close:focus-visible/);
  assert.match(css, /\.ss-economy-asset-close:focus-visible\s*\{[\s\S]*box-shadow:\s*0 0 0 3px/);
  assert.match(css, /\.ss-economy-asset-tab\s*\{/);
  assert.match(css, /\.ss-economy-asset-tab\.is-active,[\s\S]*\.ss-economy-asset-tab\[aria-selected="true"\]/);
  assert.match(css, /\.ss-economy-asset-search,[\s\S]*\.ss-economy-asset-custom\s*\{[\s\S]*grid-row:\s*3/);
  assert.match(css, /\.ss-economy-asset-grid\s*\{[\s\S]*grid-column:\s*1 \/ 2/);
  assert.match(css, /\.ss-economy-asset-grid\s*\{[\s\S]*grid-row:\s*4/);
  assert.match(css, /\.ss-economy-asset-grid\s*\{[\s\S]*grid-template-columns:\s*repeat\(auto-fill,\s*minmax\(172px,\s*1fr\)\)/);
  assert.match(css, /\.ss-economy-asset-grid\s*\{[\s\S]*grid-auto-rows:\s*minmax\(226px,\s*auto\)/);
  assert.match(css, /\.ss-economy-asset-preview\s*\{[\s\S]*grid-column:\s*2 \/ 3/);
  assert.match(css, /\.ss-economy-asset-preview\s*\{[\s\S]*position:\s*sticky/);
  assert.match(css, /\.ss-economy-asset-thumb\.is-unavailable::after\s*\{[\s\S]*Preview unavailable/);
  assert.match(css, /\.ss-economy-asset-tile\.is-selected/);
  assert.match(css, /\.ss-economy-asset-tile-main\s*\{/);
  assert.match(css, /\.ss-economy-asset-row-actions\s*\{[\s\S]*border-top:\s*1px solid/);
  assert.match(css, /\.ss-economy-asset-row-actions \.ss-btn\s*\{[\s\S]*white-space:\s*nowrap/);
  assert.match(css, /\.ss-economy-icon-preview-placeholder/);
  assert.match(css, /\.ss-economy-exchange-grid\s*\{/);
  assert.match(css, /\.ss-admin-pager\s*\{/);
});

test("economy item detail modal aggregates all tag sources into hashtag chips", () => {
  const js = read("docs/js/economy.js");
  const snippet = extractBetween(js, "  function formatItemDetailTagToken(raw) {", "  function formatEconomyDetailTimestamp(value) {");
  const context = {
    text(value) {
      return String(value ?? "").trim();
    },
    firstPresent(...values) {
      for (const value of values) {
        if (value === undefined || value === null) continue;
        if (Array.isArray(value)) {
          if (value.length) return value;
          continue;
        }
        if (typeof value === "object") return value;
        const textValue = String(value).trim();
        if (textValue) return value;
      }
      return "";
    }
  };
  vm.runInNewContext(`${snippet}
this.normalizeItemDetailTags = normalizeItemDetailTags;
this.collectEconomyItemDetailTagSources = collectEconomyItemDetailTagSources;`, context, { filename: "economy-item-detail-tags.js" });

  assert.equal(context.normalizeItemDetailTags("limo, limousine, Cadillac").join("|"), "limo|limousine|cadillac");
  assert.equal(context.normalizeItemDetailTags(["limo", "limousine", "Cadillac"]).length, 3);
  assert.equal(
    context.normalizeItemDetailTags([{ label: "limo" }, { name: "limousine" }, { value: "Cadillac" }]).join("|"),
    "limo|limousine|cadillac"
  );
  assert.equal(
    context.normalizeItemDetailTags(
      ...context.collectEconomyItemDetailTagSources(
        { item_code: "vehicle.limo" },
        { tags: ["limousine", "Cadillac"] },
        { tags: ["limo"] }
      )
    ).join("|"),
    "limo|limousine|cadillac"
  );
  assert.equal(
    context.normalizeItemDetailTags(
      ...context.collectEconomyItemDetailTagSources({ attributes: { tags: ["limo", "limousine", "Cadillac"] } }, {}, {})
    ).join("|"),
    "limo|limousine|cadillac"
  );
  assert.match(js, /data-item-detail-previous/);
  assert.match(js, /renderItemDetailCurrencyAmount\(stat\.rawValue\)/);
  assert.match(js, /variant: "item-code"/);
});

test("economy exchange controls preview held gem and diamond values", () => {
  const js = read("docs/js/economy.js");
  const css = read("docs/css/components.css");

  assert.match(js, /function renderExchangeActions\(\)/);
  assert.match(js, /state\.detail\?\.exchangeable_items/);
  assert.match(js, /No exchangeable held gems or diamonds/);
  assert.match(js, /Gems and diamonds cannot be purchased here/);
  assert.match(js, /id="economy-exchange-item"/);
  assert.match(js, /id="economy-exchange-quantity"/);
  assert.match(js, /id="economy-exchange-value"/);
  assert.match(js, /id="economy-exchange-reason"/);
  assert.match(js, /function syncExchangePreview\(\)/);
  assert.match(js, /quantity \* Number\(item\.value_in_credits \|\| 0\)/);
  assert.match(js, /await requestJson\(ECONOMY_EXCHANGE\(state\.selectedIdentityCode\)/);
  assert.match(css, /\.ss-economy-exchange-preview/);
});

test("economy identity avatars consume normalized runtime image fields and fallback", () => {
  const js = read("docs/js/economy.js");

  assert.match(js, /image\.avatar_url/);
  assert.match(js, /profileMedia\.profile_image_url/);
  assert.match(js, /identity\.profile_image_url/);
  assert.match(js, /identity\.provider_picture/);
  assert.match(js, /identity\.picture/);
  assert.match(js, /media\.avatar_url/);
  assert.match(js, /profileMedia\.provider_picture/);
  assert.match(js, /media\.provider_picture/);
  assert.match(js, /find\(usableImageUrl\)/);
  assert.match(js, /!source\.includes\("\/assets\/icons\/ui\/profile\.svg"\)/);
  assert.match(js, /image\.image_version/);
  assert.match(js, /parsed\.searchParams\.set\("v", cacheKey\)/);
  assert.match(js, /parsed\.origin !== window\.location\.origin\) return avatarUrl/);
  assert.match(js, /onerror="this\.closest\('\.ss-economy-avatar'\)\?\.classList\.remove\('has-image'\)/);
  assert.doesNotMatch(js, /Date\.now\(\)/);
});
